language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
  - master
  - "/^v?[0-9\\.]+$/"
php:
- 5.6
- 7.2
env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=0
  global:
  - SVN_REPO: https://plugins.svn.wordpress.org/kuroneko-pay/
  - secure: "pUk2PAcIwCZovOTaiI2kC1/yoBbkZsneoN2FCgMqgnH7wAW53sqklYOaxb4r7WVZD1EHEWnTBpmerJkj2FhpKuNeD3eZ6qoHtDzvEdRmYvUYGZydBlmR7GEIxfpII69kmdy/KZJnLHGw27pZ7TwbLE0RSJws4BoUEkyjrJ63AxKAYIn/CDww6liDKayW79PV+qTXbUJ7gT19FnoTUnJktdH6ybyF/FO2RUwXRDiXat330WvRoO43sZSKmNjCwJocgklALu0E5YU1sUbFl4EOOgbGg7LB1nUMLmRzKdjMaPbm3dRDZbyQgCiy7Vi4PreeP7EE3RlA2DeA1jg36bJr+aPRfvSRPSU6WsKVL74XqsxW7EeAykogvJGhYi08X7O6+VLWVvdzb8Tyi8Ai0tImJBkHtc/aueCgtPVESWuc6RbBpZ5yhINZPn8WLEuvPItao2f34RtwwdbEC+MPRgHggyaon+TYtLhwW4217v07zEgsqV2y18Q0PP+vnXgYh1QLmXM+P5aWACkY1yh3WH/UjGTXYeCzjAPEQWZUOIS2qCavSRxImw/cYoCx2nhfrOVgzZNyoxxB7CJ810+q73KyNbkgXlkH1pHB3zbIcNi/6naruaxCvQdMPcU0/W63eSebhkPEqClUvvPaRQdT/CBGEWEIUDN8RW1NvTV1YiKMenc="
matrix:
  include:
  - php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
before_script:
- composer install
- curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.8/nvm.sh
- source $HOME/.nvm/nvm.sh
- nvm install v6.11.0
- node --version
- npm install && npm run package
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
after_success: curl -L https://raw.githubusercontent.com/fumikito/travis2wpplugin/master/deploy.sh | bash
